### ISSUE TITLE
Suggestion: allow t-att-style to accept object

### ISSUE THREAD

**Issue by caburj** [odoo/owl#1310] opened 2022-12-14 11:32 UTC
Interpret `t-att-style="{ top: '100px' }"` as `style="top: 100px;"`.

**Comment by ged-odoo** [comment] 2022-12-19 08:16
yep, we should do that in my opinion

**Comment by sdegueldre** [comment] 2023-01-11 10:28
duplicate of https://github.com/odoo/owl/issues/1116

**Closed by sdegueldre** 2023-01-11 10:28 UTC
