### ISSUE TITLE
Owl scheduler can stay indefinitely in "isRunning" state

### ISSUE THREAD

**Issue by xdu-odoo** [odoo/owl#685] opened 2020-04-16 09:39 UTC
Hi, I'm sorry but I cannot find a way to reproduce that in a simple context so here is the thing ...
We found that in "some case" the scheduler stay endlessly in "IsRunning" state making the rendering paused (our test where we're waiting for the rendering to be done was paused until timeout).

With a little investigation we found that some counter is > 0 and prevents scheduler to get out of "isRunning" state and that it's due to the existence of a task containing a fiber linked to a component which is destroyed. (@alexkuhn will probably explain this better than me ... )

We managed to fix this problem with this diff https://github.com/odoo-dev/odoo/pull/209/files/3509cc1c812fb85397d83be74b4bda4c9eb5d1f4#diff-f30e8f6350b54d28c736d28272ab2fbe (we just check that the linked component is destroyed, if it is, we return) but we don't know if it's the best way.

**Comment by ged-odoo** [comment] 2020-04-21 12:42
@xdu-odoo argh, the commit linked above does not exist anymore. Sorry, i took so long. could you relink me to the code of your fix?

@alexkuhn any clue into what is happening?

**Comment by xdu-odoo** [comment] 2020-04-21 13:00
@ged-odoo No problemo :) ! Here you are : https://github.com/odoo-dev/odoo/commit/aaca5cd3bdc1470556a10727216777531d267ffd

**Comment by alexkuhn** [comment] 2020-04-21 13:19
@ged-odoo 
Just observed symptoms, but it's quite annoying to reproduce because this only happens when we run all JS tests (including `web`).

Looks like scheduler indefinitely contains a task that it cannot resolve.
This task is a fiber that relates to a component that is flagged as destroyed.
It makes sense that this fiber should be canceled, but it looks like the fiber has a counter of `1`, which prevents it from being flushed.

I suspect this is a race condition when destroying a root component.

**Comment by ged-odoo** [comment] 2020-04-22 07:24
Hello @xdu-odoo @alexkuhn 
As far as I can tell, there are almost no way for such a situation to occur. Whenever a component is destroyed, its `isCompleted` false is set to true and this should be used by the scheduler to remove the task.

The only way to get into that situation seems to be mounting an already destroyed component. In that case, I made a fix: https://github.com/odoo/owl/pull/691/commits/1d552b45374261133ace6bf38143d11db9550976

Could you check if this solves your issue? I have no idea if that is your actual problem.

**Comment by alexkuhn** [comment] 2020-04-22 11:25
@ged-odoo 
Just tested up to 559fadb and unfortunately still have the same issue.

I don't know all the subtleties of OWL internals, especially when it comes to fibers, but the solution to the "Mounting operation cancelled" issue might give some clues. As explained in https://github.com/odoo/owl/issues/676#issuecomment-617279084, the solution consists of putting `try`/`catch` around `.mount()` and `.update()` of OWL compatibility widget (basically equivalent to `.mount()` and `.render()` of component). The `try`/`catch` around `.update()` is the one that fixes our issue, because even though the error says the mounting was cancelled, OWL marks the promise of a "update" fiber as rejected.

Maybe the problem of this issue also involves "update" fibers too? Just a guess, but maybe it sets `isCompleted` to true to either the "mount" or "update" fiber, but somehow misses marking the other fiber (possibly not `currentFiber` and never eligible for being `.complete()` or `.cancel()`?).

**Comment by ged-odoo** [comment] 2020-04-23 12:07
i really cannot find a scenario where this could happen. can any of you add a debugger or a throw new Error in the scheduler
```js
                if (task.fiber.component && task.fiber.component.__owl__.isDestroyed) {
                  throw new Error('boom')
              }
 ```
to see which test fails, and try to have a small reproducible case?

**Comment by xdu-odoo** [comment] 2020-04-23 16:03
I don't know if it helps ... but here is a traceback when a test fails.
We tried multiple time to find a small reproducible case but I don't really know what's happening so it's difficult :/ ... Maybe @alexkuhn has a better idea of how we achieved to have such a scenario but I'm not sure ...

```
owl.js:3195 Uncaught Error: boom
    at owl.js:3195
    at Array.filter (<anonymous>)
    at Scheduler.flush (owl.js:3188)
    at owl.js:3218
  | (anonymous) | @ | owl.js:3195
  | flush | @ | owl.js:3188
  | (anonymous) | @ | owl.js:3218
  | requestAnimationFrame (async) |   |  
  | scheduleTasks | @ | owl.js:3217
  | start | @ | owl.js:3144
  | (anonymous) | @ | owl.js:3167
  | addFiber | @ | owl.js:3153
  | render | @ | owl.js:3947
  | __owl__.observer.notifyCB | @ | owl.js:4369
  | set | @ | owl.js:122
  | _update | @ | message.js:398
  | mounted | @ | message.js:89
  | __callMounted | @ | owl.js:4028
  | recursiveCallMounted | @ | owl_compatibility.js:377
  | recursiveCallMounted | @ | owl_compatibility.js:375
  | recursiveCallMounted | @ | owl_compatibility.js:375
  | recursiveCallMounted | @ | owl_compatibility.js:375
  | recursiveCallMounted | @ | owl_compatibility.js:375
  | recursiveCallMounted | @ | owl_compatibility.js:375
  | on_attach_callback | @ | owl_compatibility.js:379
  | on_attach_callback | @ | owl_compatibility.js:310
  | on_attach_callback | @ | form_renderer.js:59
  | prototype.<computed> | @ | class.js:90
  | on_attach_callback | @ | abstract_controller.js:128
  | on_attach_callback | @ | form_controller.js:45
  | prototype.<computed> | @ | class.js:90
  | (anonymous) | @ | dom.js:37
  | _notify | @ | dom.js:35
  | prepend | @ | dom.js:339
  | createView | @ | test_utils_create.js:439
  | async function (async) |   |  
  | createView | @ | test_utils_create.js:357
  | (anonymous) | @ | attachment_preview_tests.js:249
  | runTest | @ | qunit-2.9.1.js:3046
  | run | @ | qunit-2.9.1.js:3032
  | (anonymous) | @ | qunit-2.9.1.js:3261
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | advanceTaskQueue | @ | qunit-2.9.1.js:2609
  | advance | @ | qunit-2.9.1.js:2595
  | advanceTestQueue | @ | qunit-2.9.1.js:2653
  | advance | @ | qunit-2.9.1.js:2598
  | (anonymous) | @ | qunit-2.9.1.js:2626
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | advanceTaskQueue | @ | qunit-2.9.1.js:2609
  | advance | @ | qunit-2.9.1.js:2595
  | unblockAndAdvanceQueue | @ | qunit-2.9.1.js:4373
  | begin | @ | qunit-2.9.1.js:4407
  | (anonymous) | @ | qunit-2.9.1.js:3648
  | setTimeout (async) |   |  
  | internalStart | @ | qunit-2.9.1.js:3639
  | resume | @ | qunit-2.9.1.js:3600
  | (anonymous) | @ | qunit-2.9.1.js:3374
  | Promise.then (async) |   |  
  | resolvePromise | @ | qunit-2.9.1.js:3373
  | runTest | @ | qunit-2.9.1.js:3047
  | run | @ | qunit-2.9.1.js:3032
  | (anonymous) | @ | qunit-2.9.1.js:3261
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | advanceTaskQueue | @ | qunit-2.9.1.js:2609
  | advance | @ | qunit-2.9.1.js:2595
  | advanceTestQueue | @ | qunit-2.9.1.js:2653
  | advance | @ | qunit-2.9.1.js:2598
  | (anonymous) | @ | qunit-2.9.1.js:2626
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | advanceTaskQueue | @ | qunit-2.9.1.js:2609
  | advance | @ | qunit-2.9.1.js:2595
  | unblockAndAdvanceQueue | @ | qunit-2.9.1.js:4373
  | begin | @ | qunit-2.9.1.js:4407
  | (anonymous) | @ | qunit-2.9.1.js:3648
  | setTimeout (async) |   |  
  | internalStart | @ | qunit-2.9.1.js:3639
  | resume | @ | qunit-2.9.1.js:3600
  | (anonymous) | @ | qunit-2.9.1.js:3374
  | Promise.then (async) |   |  
  | resolvePromise | @ | qunit-2.9.1.js:3373
  | runTest | @ | qunit-2.9.1.js:3047
  | run | @ | qunit-2.9.1.js:3032
  | (anonymous) | @ | qunit-2.9.1.js:3261
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | advanceTaskQueue | @ | qunit-2.9.1.js:2609
  | advance | @ | qunit-2.9.1.js:2595
  | advanceTestQueue | @ | qunit-2.9.1.js:2653
  | advance | @ | qunit-2.9.1.js:2598
  | (anonymous) | @ | qunit-2.9.1.js:2626
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | advanceTaskQueue | @ | qunit-2.9.1.js:2609
  | advance | @ | qunit-2.9.1.js:2595
  | unblockAndAdvanceQueue | @ | qunit-2.9.1.js:4373
  | begin | @ | qunit-2.9.1.js:4407
  | (anonymous) | @ | qunit-2.9.1.js:3648
  | setTimeout (async) |   |  
  | internalStart | @ | qunit-2.9.1.js:3639
  | resume | @ | qunit-2.9.1.js:3600
  | (anonymous) | @ | qunit-2.9.1.js:3374
  | Promise.then (async) |   |  
  | resolvePromise | @ | qunit-2.9.1.js:3373
  | runTest | @ | qunit-2.9.1.js:3047
  | run | @ | qunit-2.9.1.js:3032
  | (anonymous) | @ | qunit-2.9.1.js:3261
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | advanceTaskQueue | @ | qunit-2.9.1.js:2609
  | advance | @ | qunit-2.9.1.js:2595
  | advanceTestQueue | @ | qunit-2.9.1.js:2653
  | advance | @ | qunit-2.9.1.js:2598
  | (anonymous) | @ | qunit-2.9.1.js:2626
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
  | Promise.then (async) |   |  
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | advanceTaskQueue | @ | qunit-2.9.1.js:2609
  | advance | @ | qunit-2.9.1.js:2595
  | unblockAndAdvanceQueue | @ | qunit-2.9.1.js:4373
  | begin | @ | qunit-2.9.1.js:4407
  | (anonymous) | @ | qunit-2.9.1.js:3648
  | setTimeout (async) |   |  
  | internalStart | @ | qunit-2.9.1.js:3639
  | resume | @ | qunit-2.9.1.js:3600
  | (anonymous) | @ | qunit-2.9.1.js:3374
  | Promise.then (async) |   |  
  | resolvePromise | @ | qunit-2.9.1.js:3373
  | runTest | @ | qunit-2.9.1.js:3047
  | run | @ | qunit-2.9.1.js:3032
  | (anonymous) | @ | qunit-2.9.1.js:3261
  | processTaskQueue | @ | qunit-2.9.1.js:2624
  | (anonymous) | @ | qunit-2.9.1.js:2628
```

**Comment by ged-odoo** [comment] 2022-02-15 10:26
probably fixed in owl 2 (completely new rewrite anyway)

**Closed by ged-odoo** 2022-02-15 10:26 UTC
