### ISSUE TITLE
Mounting operation cancelled

### ISSUE THREAD

**Issue by alexkuhn** [odoo/owl#676] opened 2020-03-17 14:06 UTC
**JS**
```js
const { Component } = owl;

class App extends Component {}

const app = new App();

function makeAppTarget() {
    const appTarget = document.querySelector('.app-target');
    if (appTarget) {
        document.body.removeChild(document.querySelector('.app-target'));
    }
    const div = document.createElement('div');
    div.className = 'app-target';
    document.body.append(div);   
}

async function mountApp() {
    app.mount(document.querySelector('.app-target'));
}

makeAppTarget();
mountApp();
makeAppTarget();
mountApp();
```

**XML**
```xml
<templates>
  <div t-name="App" class="app">App</div>
</templates>
```

**Error**
```
owl.js:3176 Uncaught (in promise) Error: Mounting operation cancelled
    at Scheduler.rejectFiber (owl.js:3176)
    at App.mount (owl.js:3872)
    at mountApp (<anonymous>:27:9)
    at <anonymous>:33:1
    at HTMLScriptElement.<anonymous> (app.js:98)
```

**Comment by seb-odoo** [comment] 2020-04-16 09:01
Hello, what is the status of this issue?

**Comment by ged-odoo** [comment] 2020-04-21 12:47
@alexkuhn What is the issue? You mounted your component twice, but the first mount failed because when it was ready, the target was no longer in DOM. This is working as intended. Your code has the complete information on the success or failure of the mount operation

**Comment by ged-odoo** [comment] 2020-04-21 12:47
I'll close this issue meanwhile. If you believe that I am wrong, don't hesitate to reopen it

**Closed by ged-odoo** 2020-04-21 12:47 UTC

**Comment by alexkuhn** [comment] 2020-04-21 12:54
Sorry I forgot to be more explicit on this issue.
I think the information is correct, in that the 1st render (mount) has been cancelled. However, the error is not silently handled in OWL and instead is propagated to business code.

I think this is just a small issue with this LOC: https://github.com/odoo/owl/blob/master/src/component/scheduler.ts#L67
Just saving the `reason` in `fiber.error` should fix the issue.

**Comment by ged-odoo** [comment] 2020-04-21 15:43
I am not sure I understand. Do you want a more explicit error message?

The line you linked actually make sure that the error has the reason in its message.

**Comment by alexkuhn** [comment] 2020-04-21 16:47
My bad, I thought it was a error that just had to be managed inside OWL. We fixed our issue by putting `try { } catch {}` around `.mount()` and `.update()` (in our case, the promise rejection is intercepted in a `.update()`).

The error message is explicit enough, so I wouldn't change it. Thanks!

**Comment by ged-odoo** [comment] 2020-04-21 19:10
I am not sure I understand. Do you want a more explicit error message?

The line you linked actually make sure that the error has the reason in its message.

**Comment by ged-odoo** [comment] 2020-04-21 19:12
Owl does react internally correctly to the error. It could just not throw the error, but then there would not be a way for the caller to be notified that the mounting operation failed.
