### ISSUE TITLE
owl2: remove support for function body expressions since we now support arrow functions

### ISSUE THREAD

**Issue by sdegueldre** [odoo/owl#876] opened 2021-06-17 08:16 UTC
```xml
<button t-on-click="value++"/>
<!-- becomes -->
<button t-on-click="() => value++"/>
```

At the moment, it seems that arrow functions are not supported in event handlers because we support function body expressions, but this means that some things are not possible, like calling a handler with another value from the scope on top of the event:

```xml
<!-- Not supported -->
<button t-on-click="ev => handleEvent(ev, scopeValue)"/>
```

**Comment by seb-odoo** [comment] 2021-06-18 12:07
I was about the report the same issue.

The problem is not whether or not we need to use the arrow (it actually works without it), the problem is that `ev` is taken from the scope (at the time of the render) instead of being taken from the handler param itself.

This is the generated code:
```js
       const threadView_1361 = scope['threadView'];
       const e_1361 = scope['e'];
       p1360.on['click'] = function (e) {if (context.__owl__.status === 5){return}threadView_1361.onClickHideMemberList(e_1361)};
```

And I'm hoping instead it would be:
```js
       const threadView_1361 = scope['threadView'];
       p1360.on['click'] = function (e) {if (context.__owl__.status === 5){return}threadView_1361.onClickHideMemberList(e)};
```
Notice how it keeps `e` intact, instead of transforming it into `e_1361`.

**Comment by seb-odoo** [comment] 2021-06-18 12:17
Also just to clarify, as opposed to what the title says, I think it should be a fix in current OWL, instead of being removed in OWL 2.

**Comment by seb-odoo** [comment] 2021-06-18 12:18
Looks like a duplicate of https://github.com/odoo/owl/issues/572

**Comment by sdegueldre** [comment] 2021-06-18 18:06
I think what you want in this particular case can be achieved by binding the event to some magic variable (I think @ged-odoo proposed something like $ev) that won't be looked up in the scope, and that would close #572 as well, and this is probably something we want to fix in owl 1

This issue is more about the consistency of what expressions are allowed and how they're evaluated, by allowing arrow functions in handlers the problem disappears, but also, if we don't assume that dotted expressions are function bodies, but should simply be evaluated within the scope and the returned function bound as a handler, your example could just become `t-on-click="threadView.onClickHideMemberList"`, and you would only need arrow functions when you need to pass some value from the scope to the handler and not just the event (as in my "not supported" example), but obviously this is a pretty significant breaking change to existing semantics so we probably only want to do this for the next major version.

**Closed** 2022-02-15 16:21 UTC
